import json
import os


def build_flag(model_name, **kwargs):
    keys = kwargs.keys()
    for key in keys:
        model_name += "_" + key + str(kwargs[key])
    return model_name


class BaseConfig:
    """
        Base class for constructing a ``TrainableModule(BaseConfig)``.

        There are two ways to use this class:

        1. **Extending this class**:

           You can create a custom configuration class by inheriting from ``BaseConfig``:

           Example::

           >>> class YourConfig(BaseConfig):
           >>>    def __init__(self):
           >>>        super().__init__()
           >>>        self.batch_size = 16
           >>>        self.epoch = 100
           >>>
           >>> config = YourConfig()
           >>> model = Model(config)  # Model is a subclass of TrainableModule.

           This method enables IDE code hints but requires defining a new class.

           Additionally, by overriding the `model_flag` attribute, users can customize the storage path of the trained model,
           making it easier to infer the training configuration directly from the model’s training folder name.
           The `model_flag` generated by this method reflects configuration changes made before instantiating the model.

           When overriding, define the generation rule for `model_flag` and return it.
           It is recommended to use the `train.build_flag` method from the train package for direct wrapping.

           **Note:** The ``@property`` decorator is mandatory.

           Example of overriding::

           >>>    @property
           >>>    def model_flag(self):
           >>>        return build_flag("MyModel", batch_size=self.batch_size, epoch=self.epoch)

        2. **Managing hyperparameter dynamics**:

           Hyperparameters can also be managed dynamically without creating a subclass:

           Example:

           >>> config = BaseConfig()
           >>> config.add_param("batch_size", 16)
           >>> config.add_param("epoch", 100)
           >>> model = Model(config)  # Model is a subclass of TrainableModule.

           This method is simpler and faster but does not provide IDE support for auto-completion.
           Additionally, ``model_flag`` cannot be manually modified and is generally used for quick testing.
        """

    def __init__(self):
        self.device = "cuda"

    def add_param(self,
                  param: str,
                  default_value):
        if param.startswith("_") or param.startswith("__"):
            raise ValueError("The param name '{}' which starting with '_' or '__' is not usable for Config objects."
                             "It should be added by '__setattr__(param, default_value)' method.")
        self.__setattr__(param, default_value)

    def del_param(self,
                  param: str):
        self.__delattr__(param)

    def get_params(self):
        return self.__dict__

    def save(self, path):
        """
        This method saves the hyperparameters of the model to the specified path.

        :param path: the absolute path to the saved hyperparameters.
        """
        config_json = json.dumps(self.get_params(), indent=4)
        with open(os.path.join(path, "config.json"), "w") as file:
            file.write(config_json)

    def load(self, path):
        """
        This method loads a **json-format** config file of the model from the specified path.

        :param path: absolute path to the saved json file.
        """
        with open(path, "r") as file:
            config_json = json.load(file)
        for p in config_json.keys():
            self.add_param(p, config_json[p])
        return self

    @property
    def model_flag(self):
        return build_flag("model")
